name: Hello, world! (JS)
description: "A simple GitHub Action written in JavaScript"
branding:
  icon: "clipboard"
  color: yellow
inputs:
  greeting:
    description: "Custom media type in the Accept header"
    required: false
    default: "world"
outputs:
  greeting:
    description: "The full greeting text"
runs:
  using: "node12"
  main: "dist/index.js"
